# for cargo-release
# https://github.com/crate-ci/cargo-release/blob/master/docs/faq.md#maintaining-changelog
# https://github.com/crate-ci/cargo-release/blob/master/docs/reference.md#config-fields
pre-release-replacements = [
  {file="CHANGELOG.md", search="\\[Unreleased\\]", replace="[Unreleased]\n\n## [{{version}}] - {{date}}"}
]
tag = false
push = false
